services:
  postgres:
    image: 'postgres:latest'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=master'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
  redis:
    image: 'redis:latest'
    restart: 'always'
    ports:
      - '6379:6379'
